language: python

python:
    - 2.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-dev libffi-dev libssl-dev libjpeg-dev

script:
  - |
    cd ..
    tar cfz master.tar.gz community
    pip install -U pip setuptools

  - git clone https://github.com/cuckoosandbox/cuckoo.git
  - cd cuckoo

  - git checkout 2.0-rc1
  - sed -i 's/.*pefile.*//g' requirements.txt
  - pip install -r requirements.txt
  - python utils/community.py -waf ../master.tar.gz >/dev/null
  - python cuckoo.py -d 2>&1|grep "Unable to bind ResultServer"
  - rm -rf * && git checkout .

  - git checkout 2.0-rc2
  - sed -i s/lxml==3.6.0//g requirements.txt
  - sed -i s/peepdf==0.3.2//g requirements.txt
  - pip install -r requirements.txt
  - python utils/community.py -waf ../master.tar.gz >/dev/null
  - python cuckoo.py -d 2>&1|grep "Unable to bind ResultServer"
  - rm -rf * && git checkout .

  - git checkout legacy
  - sed -i s/lxml==3.6.0//g requirements.txt
  - sed -i s/peepdf==0.3.2//g requirements.txt
  - pip install -r requirements.txt
  - python utils/community.py -waf ../master.tar.gz >/dev/null
  - python cuckoo.py -d 2>&1|grep "Unable to bind ResultServer"
  - rm -rf * && git checkout .

  - git checkout 2.0.0
  - cp -rf ../community/data/monitor/* cuckoo/data/monitor
  - git checkout cuckoo/data/monitor/latest
  - python setup.py develop
  - cuckoo init
  - cuckoo community --file ../master.tar.gz
  - cuckoo -d 2>&1|grep "Unable to bind ResultServer"
  - rm -rf ~/.cuckoo

  - git checkout master
  - cp -rf ../community/data/monitor/* cuckoo/data/monitor
  - git checkout cuckoo/data/monitor/latest
  - pip uninstall -y cuckoo idna
  - python setup.py develop
  - cuckoo init
  - cuckoo community --file ../master.tar.gz
  - cuckoo -d 2>&1|grep "Unable to bind ResultServer"
  - rm -rf ~/.cuckoo
